openapi: 3.0.2
info:
  title: New API
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
  contact: { }
paths:
  /histories:
    summary: path to show list of operations.
    description: entdpoint used to list of math operations.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/history'
          description: Successful response - returns an array of `history`.
      operationId: getHistories
      summary: List All histories
      description: Endpoint used to get the list of math operations.

  '/histories/{id}':
    summary: Path used to show a single history.
    description: The  endpoint/path used to get single math operation from history.
    parameters:
      - name: id
        in: path
        required: true
        description: The id of one math operation
        schema:
          type: number
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/history'
          description: Successful response - returns a single `history`.
      operationId: getHistory
      summary: get a single histry
      description: Gets the details of a single instance of a `history`.


  /suma:
    summary: math operations
    description: >-
      endpoint used to do sum operations.
    post:
      requestBody:
        description: A new `calculator` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calculatorSuma'
        required: true
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
      operationId: suma
      summary: sumar
      description: Creates a new instance of a `calculator`.
  /resta:
    summary: math operations
    description: >-
     endpoint used to do subtract operations.

    post:
      requestBody:
        description: A new `calculator` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calculatorResta'
        required: true
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
      operationId: resta
      summary: restar
      description: Restar dos numeros.
components:
  schemas:
    number:
      format: double
      type: number
      example: 1.0
    calculatorResta:
      title: Root Type for calculatorResta
      description: ''
      type: object
      required:
        - x
        - y
      properties:
        x:
          $ref: '#/components/schemas/number'

        y:
          $ref: '#/components/schemas/number'

        operation:
          type: string
          example: "-"

    calculatorSuma:
      title: Root Type for calculatorSuma
      description: ''
      type: object
      required:
        - x
        - y
      properties:
        x:
          $ref: '#/components/schemas/number'

        y:
          $ref: '#/components/schemas/number'

        operation:
          type: string
          example: "+"

    history:
      title: Root Type for history
      description: get history of math operations
      type: object
      required:
        - id
        - operation
        - result
        - dateTime
      properties:
        id:
          format: int64
          type: integer
          example: 1

        operation:
          type: string
          enum:
            - "+"
            - "-"

        x:
         $ref: '#/components/schemas/number'


        y:
          $ref: '#/components/schemas/number'


        result:
          $ref: '#/components/schemas/number'

        dateTime:
          format: date-time
          type: string
          example: 2021-09-21T10:15:30
