openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
    contact: {}
paths:
    /suma:
        summary: math operations
        description: >-
            The REST endpoint/path used to list and create zero or more `calculator` entities.  This path
            contains a `GET` and `POST` operation to perform the list and create tasks, respectively.

        post:
            requestBody:
                description: A new `calculator` to be created.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/calculator'
                required: true
            responses:
                '200':
                    description: Successful response.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: number
            operationId: suma
            summary: sumar
            description: Creates a new instance of a `calculator`.
    /resta:
        summary: math operations
        description: >-
            The REST endpoint/path used to list and create zero or more `calculator` entities.  This path
            contains a `GET` and `POST` operation to perform the list and create tasks, respectively.

        post:
            requestBody:
                description: A new `calculator` to be created.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/calculator'
                required: true
            responses:
                '200':
                    description: Successful response.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: number
            operationId: resta
            summary: restar
            description: Creates a new instance of a `calculator`.
components:
    schemas:
        calculator:
            title: Root Type for calculator
            description: ''
            type: object
            properties:
                x:
                    format: double
                    type: number
                y:
                    format: double
                    type: number

            example:
                x: 1.0
                y: 2.0

